### ISSUE TITLE
unhandledError: std.file.FileException@std/file.d(4642): public: No such file or directory

### ISSUE THREAD

**Issue by csdlee** [DiamondMVC/Diamond#139]
unhandledError: std.file.FileException@std/file.d(4642): public: No such file or directory

diamond-empty-project ~master: target for configuration "application" is up to date.
To force a rebuild of up-to-date targets, run again with --force.
Running ./diamond-empty-project 
unhandledError: std.file.FileException@std/file.d(4642): public: No such file or directory
??:? @safe core.sys.posix.dirent.DIR* std.file.cenforce!(core.sys.posix.dirent.DIR*).cenforce(core.sys.posix.dirent.DIR*, scope lazy const(char)[], immutable(char)[], ulong) [0x149f70fb]
??:? @safe bool std.file.DirIteratorImpl.stepIn(immutable(char)[]) [0x149f5da5]
??:? ref @safe std.file.DirIteratorImpl std.file.DirIteratorImpl.__ctor!(immutable(char)[]).__ctor(immutable(char)[], std.file.SpanMode, bool) [0x14a3b2b8]
??:? ref @safe std.conv.emplaceRef!(std.file.DirIteratorImpl, std.file.DirIteratorImpl, immutable(char)[], std.file.SpanMode, bool).emplaceRef(ref std.file.DirIteratorImpl, ref immutable(char)[], ref std.file.SpanMode, ref bool).S std.conv.emplaceRef!(std.file.DirIteratorImpl, std.file.DirIteratorImpl, immutable(char)[], std.file.SpanMode, bool).emplaceRef(ref std.file.DirIteratorImpl, ref immutable(char)[], ref std.file.SpanMode, ref bool).S.__ctor(ref immutable(char)[], ref std.file.SpanMode, ref bool) [0x14a37096]
??:? @safe void std.conv.emplaceRef!(std.file.DirIteratorImpl, std.file.DirIteratorImpl, immutable(char)[], std.file.SpanMode, bool).emplaceRef(ref std.file.DirIteratorImpl, ref immutable(char)[], ref std.file.SpanMode, ref bool) [0x14a3703e]
??:? @safe std.file.DirIteratorImpl* std.conv.emplace!(std.file.DirIteratorImpl, immutable(char)[], std.file.SpanMode, bool).emplace(std.file.DirIteratorImpl*, ref immutable(char)[], ref std.file.SpanMode, ref bool) [0x14a36ff0]
??:? void std.typecons.RefCounted!(std.file.DirIteratorImpl, 0).RefCounted.RefCountedStore.initialize!(immutable(char)[], std.file.SpanMode, bool).initialize(ref immutable(char)[], ref std.file.SpanMode, ref bool) [0x14a03717]
??:? ref std.typecons.RefCounted!(std.file.DirIteratorImpl, 0).RefCounted std.typecons.RefCounted!(std.file.DirIteratorImpl, 0).RefCounted.__ctor!(immutable(char)[], std.file.SpanMode, bool).__ctor(ref immutable(char)[], ref std.file.SpanMode, ref bool) [0x14a036ac]
??:? ref @trusted std.file.DirIterator std.file.DirIterator.__ctor(immutable(char)[], std.file.SpanMode, bool) [0x149f6531]
??:? std.file.DirIterator std.file.dirEntries(immutable(char)[], std.file.SpanMode, bool) [0x149f6724]
../../../.dub/packages/diamond-2.10.1/diamond/init/web.d:202 void diamond.init.web.loadStaticFiles() [0x147786b6]
../../../.dub/packages/diamond-2.10.1/diamond/init/web.d:79 void diamond.init.web.runDiamond() [0x14776f2c]
../../../.dub/packages/diamond-2.10.1/diamond/init/web.d:35 _Dmain [0x14776e8c]
std.file.FileException@std/file.d(4642): public: No such file or directory
??:? @safe core.sys.posix.dirent.DIR* std.file.cenforce!(core.sys.posix.dirent.DIR*).cenforce(core.sys.posix.dirent.DIR*, scope lazy const(char)[], immutable(char)[], ulong) [0x149f70fb]
??:? @safe bool std.file.DirIteratorImpl.stepIn(immutable(char)[]) [0x149f5da5]
??:? ref @safe std.file.DirIteratorImpl std.file.DirIteratorImpl.__ctor!(immutable(char)[]).__ctor(immutable(char)[], std.file.SpanMode, bool) [0x14a3b2b8]
??:? ref @safe std.conv.emplaceRef!(std.file.DirIteratorImpl, std.file.DirIteratorImpl, immutable(char)[], std.file.SpanMode, bool).emplaceRef(ref std.file.DirIteratorImpl, ref immutable(char)[], ref std.file.SpanMode, ref bool).S std.conv.emplaceRef!(std.file.DirIteratorImpl, std.file.DirIteratorImpl, immutable(char)[], std.file.SpanMode, bool).emplaceRef(ref std.file.DirIteratorImpl, ref immutable(char)[], ref std.file.SpanMode, ref bool).S.__ctor(ref immutable(char)[], ref std.file.SpanMode, ref bool) [0x14a37096]
??:? @safe void std.conv.emplaceRef!(std.file.DirIteratorImpl, std.file.DirIteratorImpl, immutable(char)[], std.file.SpanMode, bool).emplaceRef(ref std.file.DirIteratorImpl, ref immutable(char)[], ref std.file.SpanMode, ref bool) [0x14a3703e]
??:? @safe std.file.DirIteratorImpl* std.conv.emplace!(std.file.DirIteratorImpl, immutable(char)[], std.file.SpanMode, bool).emplace(std.file.DirIteratorImpl*, ref immutable(char)[], ref std.file.SpanMode, ref bool) [0x14a36ff0]
??:? void std.typecons.RefCounted!(std.file.DirIteratorImpl, 0).RefCounted.RefCountedStore.initialize!(immutable(char)[], std.file.SpanMode, bool).initialize(ref immutable(char)[], ref std.file.SpanMode, ref bool) [0x14a03717]
??:? ref std.typecons.RefCounted!(std.file.DirIteratorImpl, 0).RefCounted std.typecons.RefCounted!(std.file.DirIteratorImpl, 0).RefCounted.__ctor!(immutable(char)[], std.file.SpanMode, bool).__ctor(ref immutable(char)[], ref std.file.SpanMode, ref bool) [0x14a036ac]
??:? ref @trusted std.file.DirIterator std.file.DirIterator.__ctor(immutable(char)[], std.file.SpanMode, bool) [0x149f6531]
??:? std.file.DirIterator std.file.dirEntries(immutable(char)[], std.file.SpanMode, bool) [0x149f6724]
../../../.dub/packages/diamond-2.10.1/diamond/init/web.d:202 void diamond.init.web.loadStaticFiles() [0x147786b6]
../../../.dub/packages/diamond-2.10.1/diamond/init/web.d:79 void diamond.init.web.runDiamond() [0x14776f2c]
../../../.dub/packages/diamond-2.10.1/diamond/init/web.d:35 _Dmain [0x14776e8c]
Program exited with code 1

 - Environment: Self-hosting
 - OS: Linux
 - Arch:x64
 - Diamond Version : 2.10.1
 -dmd 2.083

**Comment by bausshf** [comment]
This has been solved now and downloading the example project again will fix it.
